// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package redleasev1

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type ClientOperation byte

const (
	ClientOperationNONE    ClientOperation = 0
	ClientOperationACQUIRE ClientOperation = 1
	ClientOperationRENEW   ClientOperation = 2
	ClientOperationRELEASE ClientOperation = 3
	ClientOperationGET_TTL ClientOperation = 4
)

var EnumNamesClientOperation = map[ClientOperation]string{
	ClientOperationNONE:    "NONE",
	ClientOperationACQUIRE: "ACQUIRE",
	ClientOperationRENEW:   "RENEW",
	ClientOperationRELEASE: "RELEASE",
	ClientOperationGET_TTL: "GET_TTL",
}

var EnumValuesClientOperation = map[string]ClientOperation{
	"NONE":    ClientOperationNONE,
	"ACQUIRE": ClientOperationACQUIRE,
	"RENEW":   ClientOperationRENEW,
	"RELEASE": ClientOperationRELEASE,
	"GET_TTL": ClientOperationGET_TTL,
}

func (v ClientOperation) String() string {
	if s, ok := EnumNamesClientOperation[v]; ok {
		return s
	}
	return "ClientOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}

type LeaseStatus byte

const (
	LeaseStatusOK                LeaseStatus = 0
	LeaseStatusALREADY_OWNED     LeaseStatus = 1
	LeaseStatusBUSY              LeaseStatus = 2
	LeaseStatusSTALE             LeaseStatus = 3
	LeaseStatusNOT_READY         LeaseStatus = 4
	LeaseStatusKEY_LIMIT_REACHED LeaseStatus = 5
)

var EnumNamesLeaseStatus = map[LeaseStatus]string{
	LeaseStatusOK:                "OK",
	LeaseStatusALREADY_OWNED:     "ALREADY_OWNED",
	LeaseStatusBUSY:              "BUSY",
	LeaseStatusSTALE:             "STALE",
	LeaseStatusNOT_READY:         "NOT_READY",
	LeaseStatusKEY_LIMIT_REACHED: "KEY_LIMIT_REACHED",
}

var EnumValuesLeaseStatus = map[string]LeaseStatus{
	"OK":                LeaseStatusOK,
	"ALREADY_OWNED":     LeaseStatusALREADY_OWNED,
	"BUSY":              LeaseStatusBUSY,
	"STALE":             LeaseStatusSTALE,
	"NOT_READY":         LeaseStatusNOT_READY,
	"KEY_LIMIT_REACHED": LeaseStatusKEY_LIMIT_REACHED,
}

func (v LeaseStatus) String() string {
	if s, ok := EnumNamesLeaseStatus[v]; ok {
		return s
	}
	return "LeaseStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ServerResult byte

const (
	ServerResultNONE    ServerResult = 0
	ServerResultACQUIRE ServerResult = 1
	ServerResultRENEW   ServerResult = 2
	ServerResultRELEASE ServerResult = 3
	ServerResultGET_TTL ServerResult = 4
)

var EnumNamesServerResult = map[ServerResult]string{
	ServerResultNONE:    "NONE",
	ServerResultACQUIRE: "ACQUIRE",
	ServerResultRENEW:   "RENEW",
	ServerResultRELEASE: "RELEASE",
	ServerResultGET_TTL: "GET_TTL",
}

var EnumValuesServerResult = map[string]ServerResult{
	"NONE":    ServerResultNONE,
	"ACQUIRE": ServerResultACQUIRE,
	"RENEW":   ServerResultRENEW,
	"RELEASE": ServerResultRELEASE,
	"GET_TTL": ServerResultGET_TTL,
}

func (v ServerResult) String() string {
	if s, ok := EnumNamesServerResult[v]; ok {
		return s
	}
	return "ServerResult(" + strconv.FormatInt(int64(v), 10) + ")"
}

type AcquireRequest struct {
	_tab flatbuffers.Struct
}

func (rcv *AcquireRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AcquireRequest) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *AcquireRequest) Key() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *AcquireRequest) MutateKey(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *AcquireRequest) ClientId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *AcquireRequest) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *AcquireRequest) BootId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *AcquireRequest) MutateBootId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *AcquireRequest) LeaseSeq() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *AcquireRequest) MutateLeaseSeq(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *AcquireRequest) RequestedTtlMs() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *AcquireRequest) MutateRequestedTtlMs(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func CreateAcquireRequest(builder *flatbuffers.Builder, key uint64, clientId uint32, bootId uint32, leaseSeq uint64, requestedTtlMs uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 32)
	builder.PrependUint64(requestedTtlMs)
	builder.PrependUint64(leaseSeq)
	builder.PrependUint32(bootId)
	builder.PrependUint32(clientId)
	builder.PrependUint64(key)
	return builder.Offset()
}
type RenewRequest struct {
	_tab flatbuffers.Struct
}

func (rcv *RenewRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RenewRequest) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RenewRequest) Key() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *RenewRequest) MutateKey(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *RenewRequest) ClientId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *RenewRequest) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *RenewRequest) BootId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *RenewRequest) MutateBootId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *RenewRequest) LeaseSeq() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *RenewRequest) MutateLeaseSeq(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *RenewRequest) RequestedTtlMs() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(24))
}
func (rcv *RenewRequest) MutateRequestedTtlMs(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(24), n)
}

func CreateRenewRequest(builder *flatbuffers.Builder, key uint64, clientId uint32, bootId uint32, leaseSeq uint64, requestedTtlMs uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 32)
	builder.PrependUint64(requestedTtlMs)
	builder.PrependUint64(leaseSeq)
	builder.PrependUint32(bootId)
	builder.PrependUint32(clientId)
	builder.PrependUint64(key)
	return builder.Offset()
}
type ReleaseRequest struct {
	_tab flatbuffers.Struct
}

func (rcv *ReleaseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReleaseRequest) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ReleaseRequest) Key() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ReleaseRequest) MutateKey(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ReleaseRequest) ClientId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ReleaseRequest) MutateClientId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *ReleaseRequest) BootId() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *ReleaseRequest) MutateBootId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *ReleaseRequest) LeaseSeq() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *ReleaseRequest) MutateLeaseSeq(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func CreateReleaseRequest(builder *flatbuffers.Builder, key uint64, clientId uint32, bootId uint32, leaseSeq uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 24)
	builder.PrependUint64(leaseSeq)
	builder.PrependUint32(bootId)
	builder.PrependUint32(clientId)
	builder.PrependUint64(key)
	return builder.Offset()
}
/// One operation sent through a TCP connection.
type ClientRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClientRequest(buf []byte, offset flatbuffers.UOffsetT) *ClientRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientRequest(buf []byte, offset flatbuffers.UOffsetT) *ClientRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientRequest) Table() flatbuffers.Table {
	return rcv._tab
}

/// Unique within one TCP connection generation. It is echoed by the server
/// and is not a cross-reconnect deduplication key.
func (rcv *ClientRequest) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// Unique within one TCP connection generation. It is echoed by the server
/// and is not a cross-reconnect deduplication key.
func (rcv *ClientRequest) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ClientRequest) Operation() ClientOperation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ClientOperation(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientRequest) MutateOperation(n ClientOperation) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ClientRequest) Acquire(obj *AcquireRequest) *AcquireRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AcquireRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClientRequest) Renew(obj *RenewRequest) *RenewRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(RenewRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClientRequest) Release(obj *ReleaseRequest) *ReleaseRequest {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ReleaseRequest)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ClientRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ClientRequestAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func ClientRequestAddOperation(builder *flatbuffers.Builder, operation ClientOperation) {
	builder.PrependByteSlot(1, byte(operation), 0)
}
func ClientRequestAddAcquire(builder *flatbuffers.Builder, acquire flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(acquire), 0)
}
func ClientRequestAddRenew(builder *flatbuffers.Builder, renew flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(renew), 0)
}
func ClientRequestAddRelease(builder *flatbuffers.Builder, release flatbuffers.UOffsetT) {
	builder.PrependStructSlot(4, flatbuffers.UOffsetT(release), 0)
}
func ClientRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type AcquireResponse struct {
	_tab flatbuffers.Struct
}

func (rcv *AcquireResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AcquireResponse) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *AcquireResponse) Status() LeaseStatus {
	return LeaseStatus(rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *AcquireResponse) MutateStatus(n LeaseStatus) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), byte(n))
}

func (rcv *AcquireResponse) TtlMs() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *AcquireResponse) MutateTtlMs(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateAcquireResponse(builder *flatbuffers.Builder, status LeaseStatus, ttlMs uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(ttlMs)
	builder.Pad(7)
	builder.PrependByte(byte(status))
	return builder.Offset()
}
type RenewResponse struct {
	_tab flatbuffers.Struct
}

func (rcv *RenewResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RenewResponse) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RenewResponse) Status() LeaseStatus {
	return LeaseStatus(rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *RenewResponse) MutateStatus(n LeaseStatus) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), byte(n))
}

func (rcv *RenewResponse) TtlMs() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *RenewResponse) MutateTtlMs(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateRenewResponse(builder *flatbuffers.Builder, status LeaseStatus, ttlMs uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(ttlMs)
	builder.Pad(7)
	builder.PrependByte(byte(status))
	return builder.Offset()
}
type ReleaseResponse struct {
	_tab flatbuffers.Struct
}

func (rcv *ReleaseResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReleaseResponse) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ReleaseResponse) Status() LeaseStatus {
	return LeaseStatus(rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *ReleaseResponse) MutateStatus(n LeaseStatus) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), byte(n))
}

func CreateReleaseResponse(builder *flatbuffers.Builder, status LeaseStatus) flatbuffers.UOffsetT {
	builder.Prep(1, 1)
	builder.PrependByte(byte(status))
	return builder.Offset()
}
type GetTTLResponse struct {
	_tab flatbuffers.Struct
}

func (rcv *GetTTLResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetTTLResponse) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *GetTTLResponse) ConfiguredMaxTtlMs() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *GetTTLResponse) MutateConfiguredMaxTtlMs(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateGetTTLResponse(builder *flatbuffers.Builder, configuredMaxTtlMs uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependUint64(configuredMaxTtlMs)
	return builder.Offset()
}
/// One response returned through a TCP connection.
type ServerResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsServerResponse(buf []byte, offset flatbuffers.UOffsetT) *ServerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerResponse(buf []byte, offset flatbuffers.UOffsetT) *ServerResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerResponse) Table() flatbuffers.Table {
	return rcv._tab
}

/// Correlates this response with a ClientRequest on the same connection.
func (rcv *ServerResponse) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// Correlates this response with a ClientRequest on the same connection.
func (rcv *ServerResponse) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ServerResponse) Result() ServerResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ServerResult(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ServerResponse) MutateResult(n ServerResult) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *ServerResponse) Acquire(obj *AcquireResponse) *AcquireResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(AcquireResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ServerResponse) Renew(obj *RenewResponse) *RenewResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(RenewResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ServerResponse) Release(obj *ReleaseResponse) *ReleaseResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ReleaseResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ServerResponse) GetTtl(obj *GetTTLResponse) *GetTTLResponse {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(GetTTLResponse)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ServerResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ServerResponseAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func ServerResponseAddResult(builder *flatbuffers.Builder, result ServerResult) {
	builder.PrependByteSlot(1, byte(result), 0)
}
func ServerResponseAddAcquire(builder *flatbuffers.Builder, acquire flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(acquire), 0)
}
func ServerResponseAddRenew(builder *flatbuffers.Builder, renew flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(renew), 0)
}
func ServerResponseAddRelease(builder *flatbuffers.Builder, release flatbuffers.UOffsetT) {
	builder.PrependStructSlot(4, flatbuffers.UOffsetT(release), 0)
}
func ServerResponseAddGetTtl(builder *flatbuffers.Builder, getTtl flatbuffers.UOffsetT) {
	builder.PrependStructSlot(5, flatbuffers.UOffsetT(getTtl), 0)
}
func ServerResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
