#!/bin/sh
set -e

if ! getent group redlease >/dev/null; then
    addgroup --system redlease
fi
if ! getent passwd redlease >/dev/null; then
    adduser \
        --system \
        --ingroup redlease \
        --home / \
        --no-create-home \
        --shell /usr/sbin/nologin \
        --disabled-login \
        --gecos "RedLease server" \
        redlease
fi

if command -v systemctl >/dev/null && [ -d /run/systemd/system ]; then
    systemctl daemon-reload || :
    if [ -n "${2:-}" ]; then
        systemctl try-restart redlease-server.service || :
    fi
fi

exit 0
