// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: redlease/v1/redlease.proto

package redleasev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedLease_LeaseStream_FullMethodName = "/redlease.v1.RedLease/LeaseStream"
)

// RedLeaseClient is the client API for RedLease service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RedLease exposes every client operation through one persistent
// bidirectional stream per client/server pair. Responses for different keys
// may be sent out of request order and are correlated by request_id.
type RedLeaseClient interface {
	LeaseStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ServerResponse], error)
}

type redLeaseClient struct {
	cc grpc.ClientConnInterface
}

func NewRedLeaseClient(cc grpc.ClientConnInterface) RedLeaseClient {
	return &redLeaseClient{cc}
}

func (c *redLeaseClient) LeaseStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ServerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RedLease_ServiceDesc.Streams[0], RedLease_LeaseStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientRequest, ServerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedLease_LeaseStreamClient = grpc.BidiStreamingClient[ClientRequest, ServerResponse]

// RedLeaseServer is the server API for RedLease service.
// All implementations must embed UnimplementedRedLeaseServer
// for forward compatibility.
//
// RedLease exposes every client operation through one persistent
// bidirectional stream per client/server pair. Responses for different keys
// may be sent out of request order and are correlated by request_id.
type RedLeaseServer interface {
	LeaseStream(grpc.BidiStreamingServer[ClientRequest, ServerResponse]) error
	mustEmbedUnimplementedRedLeaseServer()
}

// UnimplementedRedLeaseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedLeaseServer struct{}

func (UnimplementedRedLeaseServer) LeaseStream(grpc.BidiStreamingServer[ClientRequest, ServerResponse]) error {
	return status.Error(codes.Unimplemented, "method LeaseStream not implemented")
}
func (UnimplementedRedLeaseServer) mustEmbedUnimplementedRedLeaseServer() {}
func (UnimplementedRedLeaseServer) testEmbeddedByValue()                  {}

// UnsafeRedLeaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedLeaseServer will
// result in compilation errors.
type UnsafeRedLeaseServer interface {
	mustEmbedUnimplementedRedLeaseServer()
}

func RegisterRedLeaseServer(s grpc.ServiceRegistrar, srv RedLeaseServer) {
	// If the following call panics, it indicates UnimplementedRedLeaseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedLease_ServiceDesc, srv)
}

func _RedLease_LeaseStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RedLeaseServer).LeaseStream(&grpc.GenericServerStream[ClientRequest, ServerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedLease_LeaseStreamServer = grpc.BidiStreamingServer[ClientRequest, ServerResponse]

// RedLease_ServiceDesc is the grpc.ServiceDesc for RedLease service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedLease_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redlease.v1.RedLease",
	HandlerType: (*RedLeaseServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LeaseStream",
			Handler:       _RedLease_LeaseStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "redlease/v1/redlease.proto",
}
