// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: redlease/v1/redlease.proto

package redleasev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseStatus int32

const (
	LeaseStatus_LEASE_STATUS_OK                LeaseStatus = 0
	LeaseStatus_LEASE_STATUS_ALREADY_OWNED     LeaseStatus = 1
	LeaseStatus_LEASE_STATUS_BUSY              LeaseStatus = 2
	LeaseStatus_LEASE_STATUS_STALE             LeaseStatus = 3
	LeaseStatus_LEASE_STATUS_NOT_READY         LeaseStatus = 4
	LeaseStatus_LEASE_STATUS_KEY_LIMIT_REACHED LeaseStatus = 5
	LeaseStatus_LEASE_STATUS_KEY_TOO_LARGE     LeaseStatus = 6
)

// Enum value maps for LeaseStatus.
var (
	LeaseStatus_name = map[int32]string{
		0: "LEASE_STATUS_OK",
		1: "LEASE_STATUS_ALREADY_OWNED",
		2: "LEASE_STATUS_BUSY",
		3: "LEASE_STATUS_STALE",
		4: "LEASE_STATUS_NOT_READY",
		5: "LEASE_STATUS_KEY_LIMIT_REACHED",
		6: "LEASE_STATUS_KEY_TOO_LARGE",
	}
	LeaseStatus_value = map[string]int32{
		"LEASE_STATUS_OK":                0,
		"LEASE_STATUS_ALREADY_OWNED":     1,
		"LEASE_STATUS_BUSY":              2,
		"LEASE_STATUS_STALE":             3,
		"LEASE_STATUS_NOT_READY":         4,
		"LEASE_STATUS_KEY_LIMIT_REACHED": 5,
		"LEASE_STATUS_KEY_TOO_LARGE":     6,
	}
)

func (x LeaseStatus) Enum() *LeaseStatus {
	p := new(LeaseStatus)
	*p = x
	return p
}

func (x LeaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_redlease_v1_redlease_proto_enumTypes[0].Descriptor()
}

func (LeaseStatus) Type() protoreflect.EnumType {
	return &file_redlease_v1_redlease_proto_enumTypes[0]
}

func (x LeaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseStatus.Descriptor instead.
func (LeaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{0}
}

type LeaseID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint32                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BootId        uint32                 `protobuf:"varint,2,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	LeaseSeq      uint64                 `protobuf:"varint,3,opt,name=lease_seq,json=leaseSeq,proto3" json:"lease_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseID) Reset() {
	*x = LeaseID{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseID) ProtoMessage() {}

func (x *LeaseID) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseID.ProtoReflect.Descriptor instead.
func (*LeaseID) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseID) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaseID) GetBootId() uint32 {
	if x != nil {
		return x.BootId
	}
	return 0
}

func (x *LeaseID) GetLeaseSeq() uint64 {
	if x != nil {
		return x.LeaseSeq
	}
	return 0
}

type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within one LeaseStream. It is echoed by the server and is not a
	// cross-reconnect deduplication key.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*ClientRequest_Acquire
	//	*ClientRequest_Renew
	//	*ClientRequest_Release
	//	*ClientRequest_GetTtl
	Operation     isClientRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ClientRequest) GetOperation() isClientRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ClientRequest) GetAcquire() *AcquireRequest {
	if x != nil {
		if x, ok := x.Operation.(*ClientRequest_Acquire); ok {
			return x.Acquire
		}
	}
	return nil
}

func (x *ClientRequest) GetRenew() *RenewRequest {
	if x != nil {
		if x, ok := x.Operation.(*ClientRequest_Renew); ok {
			return x.Renew
		}
	}
	return nil
}

func (x *ClientRequest) GetRelease() *ReleaseRequest {
	if x != nil {
		if x, ok := x.Operation.(*ClientRequest_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *ClientRequest) GetGetTtl() *GetTTLRequest {
	if x != nil {
		if x, ok := x.Operation.(*ClientRequest_GetTtl); ok {
			return x.GetTtl
		}
	}
	return nil
}

type isClientRequest_Operation interface {
	isClientRequest_Operation()
}

type ClientRequest_Acquire struct {
	Acquire *AcquireRequest `protobuf:"bytes,2,opt,name=acquire,proto3,oneof"`
}

type ClientRequest_Renew struct {
	Renew *RenewRequest `protobuf:"bytes,3,opt,name=renew,proto3,oneof"`
}

type ClientRequest_Release struct {
	Release *ReleaseRequest `protobuf:"bytes,4,opt,name=release,proto3,oneof"`
}

type ClientRequest_GetTtl struct {
	GetTtl *GetTTLRequest `protobuf:"bytes,5,opt,name=get_ttl,json=getTtl,proto3,oneof"`
}

func (*ClientRequest_Acquire) isClientRequest_Operation() {}

func (*ClientRequest_Renew) isClientRequest_Operation() {}

func (*ClientRequest_Release) isClientRequest_Operation() {}

func (*ClientRequest_GetTtl) isClientRequest_Operation() {}

type ServerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates this response with a ClientRequest on the same LeaseStream.
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ServerResponse_Acquire
	//	*ServerResponse_Renew
	//	*ServerResponse_Release
	//	*ServerResponse_GetTtl
	Result        isServerResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ServerResponse) GetResult() isServerResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ServerResponse) GetAcquire() *AcquireResponse {
	if x != nil {
		if x, ok := x.Result.(*ServerResponse_Acquire); ok {
			return x.Acquire
		}
	}
	return nil
}

func (x *ServerResponse) GetRenew() *RenewResponse {
	if x != nil {
		if x, ok := x.Result.(*ServerResponse_Renew); ok {
			return x.Renew
		}
	}
	return nil
}

func (x *ServerResponse) GetRelease() *ReleaseResponse {
	if x != nil {
		if x, ok := x.Result.(*ServerResponse_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *ServerResponse) GetGetTtl() *GetTTLResponse {
	if x != nil {
		if x, ok := x.Result.(*ServerResponse_GetTtl); ok {
			return x.GetTtl
		}
	}
	return nil
}

type isServerResponse_Result interface {
	isServerResponse_Result()
}

type ServerResponse_Acquire struct {
	Acquire *AcquireResponse `protobuf:"bytes,2,opt,name=acquire,proto3,oneof"`
}

type ServerResponse_Renew struct {
	Renew *RenewResponse `protobuf:"bytes,3,opt,name=renew,proto3,oneof"`
}

type ServerResponse_Release struct {
	Release *ReleaseResponse `protobuf:"bytes,4,opt,name=release,proto3,oneof"`
}

type ServerResponse_GetTtl struct {
	GetTtl *GetTTLResponse `protobuf:"bytes,5,opt,name=get_ttl,json=getTtl,proto3,oneof"`
}

func (*ServerResponse_Acquire) isServerResponse_Result() {}

func (*ServerResponse_Renew) isServerResponse_Result() {}

func (*ServerResponse_Release) isServerResponse_Result() {}

func (*ServerResponse_GetTtl) isServerResponse_Result() {}

type AcquireRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LeaseId        *LeaseID               `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RequestedTtlMs uint64                 `protobuf:"varint,3,opt,name=requested_ttl_ms,json=requestedTtlMs,proto3" json:"requested_ttl_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{3}
}

func (x *AcquireRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AcquireRequest) GetLeaseId() *LeaseID {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *AcquireRequest) GetRequestedTtlMs() uint64 {
	if x != nil {
		return x.RequestedTtlMs
	}
	return 0
}

type RenewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LeaseId        *LeaseID               `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RequestedTtlMs uint64                 `protobuf:"varint,3,opt,name=requested_ttl_ms,json=requestedTtlMs,proto3" json:"requested_ttl_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{4}
}

func (x *RenewRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RenewRequest) GetLeaseId() *LeaseID {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

func (x *RenewRequest) GetRequestedTtlMs() uint64 {
	if x != nil {
		return x.RequestedTtlMs
	}
	return 0
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LeaseId       *LeaseID               `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReleaseRequest) GetLeaseId() *LeaseID {
	if x != nil {
		return x.LeaseId
	}
	return nil
}

type GetTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTTLRequest) Reset() {
	*x = GetTTLRequest{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTTLRequest) ProtoMessage() {}

func (x *GetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTTLRequest.ProtoReflect.Descriptor instead.
func (*GetTTLRequest) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{6}
}

type AcquireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LeaseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=redlease.v1.LeaseStatus" json:"status,omitempty"`
	TtlMs         uint64                 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{7}
}

func (x *AcquireResponse) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_OK
}

func (x *AcquireResponse) GetTtlMs() uint64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LeaseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=redlease.v1.LeaseStatus" json:"status,omitempty"`
	TtlMs         uint64                 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{8}
}

func (x *RenewResponse) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_OK
}

func (x *RenewResponse) GetTtlMs() uint64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LeaseStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=redlease.v1.LeaseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseResponse) GetStatus() LeaseStatus {
	if x != nil {
		return x.Status
	}
	return LeaseStatus_LEASE_STATUS_OK
}

type GetTTLResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConfiguredMaxTtlMs uint64                 `protobuf:"varint,1,opt,name=configured_max_ttl_ms,json=configuredMaxTtlMs,proto3" json:"configured_max_ttl_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTTLResponse) Reset() {
	*x = GetTTLResponse{}
	mi := &file_redlease_v1_redlease_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTTLResponse) ProtoMessage() {}

func (x *GetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redlease_v1_redlease_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTTLResponse.ProtoReflect.Descriptor instead.
func (*GetTTLResponse) Descriptor() ([]byte, []int) {
	return file_redlease_v1_redlease_proto_rawDescGZIP(), []int{10}
}

func (x *GetTTLResponse) GetConfiguredMaxTtlMs() uint64 {
	if x != nil {
		return x.ConfiguredMaxTtlMs
	}
	return 0
}

var File_redlease_v1_redlease_proto protoreflect.FileDescriptor

const file_redlease_v1_redlease_proto_rawDesc = "" +
	"\n" +
	"\x1aredlease/v1/redlease.proto\x12\vredlease.v1\"\\\n" +
	"\aLeaseID\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\rR\bclientId\x12\x17\n" +
	"\aboot_id\x18\x02 \x01(\rR\x06bootId\x12\x1b\n" +
	"\tlease_seq\x18\x03 \x01(\x04R\bleaseSeq\"\x97\x02\n" +
	"\rClientRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x127\n" +
	"\aacquire\x18\x02 \x01(\v2\x1b.redlease.v1.AcquireRequestH\x00R\aacquire\x121\n" +
	"\x05renew\x18\x03 \x01(\v2\x19.redlease.v1.RenewRequestH\x00R\x05renew\x127\n" +
	"\arelease\x18\x04 \x01(\v2\x1b.redlease.v1.ReleaseRequestH\x00R\arelease\x125\n" +
	"\aget_ttl\x18\x05 \x01(\v2\x1a.redlease.v1.GetTTLRequestH\x00R\x06getTtlB\v\n" +
	"\toperation\"\x99\x02\n" +
	"\x0eServerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x128\n" +
	"\aacquire\x18\x02 \x01(\v2\x1c.redlease.v1.AcquireResponseH\x00R\aacquire\x122\n" +
	"\x05renew\x18\x03 \x01(\v2\x1a.redlease.v1.RenewResponseH\x00R\x05renew\x128\n" +
	"\arelease\x18\x04 \x01(\v2\x1c.redlease.v1.ReleaseResponseH\x00R\arelease\x126\n" +
	"\aget_ttl\x18\x05 \x01(\v2\x1b.redlease.v1.GetTTLResponseH\x00R\x06getTtlB\b\n" +
	"\x06result\"}\n" +
	"\x0eAcquireRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12/\n" +
	"\blease_id\x18\x02 \x01(\v2\x14.redlease.v1.LeaseIDR\aleaseId\x12(\n" +
	"\x10requested_ttl_ms\x18\x03 \x01(\x04R\x0erequestedTtlMs\"{\n" +
	"\fRenewRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12/\n" +
	"\blease_id\x18\x02 \x01(\v2\x14.redlease.v1.LeaseIDR\aleaseId\x12(\n" +
	"\x10requested_ttl_ms\x18\x03 \x01(\x04R\x0erequestedTtlMs\"S\n" +
	"\x0eReleaseRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12/\n" +
	"\blease_id\x18\x02 \x01(\v2\x14.redlease.v1.LeaseIDR\aleaseId\"\x0f\n" +
	"\rGetTTLRequest\"Z\n" +
	"\x0fAcquireResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.redlease.v1.LeaseStatusR\x06status\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x04R\x05ttlMs\"X\n" +
	"\rRenewResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.redlease.v1.LeaseStatusR\x06status\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x04R\x05ttlMs\"C\n" +
	"\x0fReleaseResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.redlease.v1.LeaseStatusR\x06status\"C\n" +
	"\x0eGetTTLResponse\x121\n" +
	"\x15configured_max_ttl_ms\x18\x01 \x01(\x04R\x12configuredMaxTtlMs*\xd1\x01\n" +
	"\vLeaseStatus\x12\x13\n" +
	"\x0fLEASE_STATUS_OK\x10\x00\x12\x1e\n" +
	"\x1aLEASE_STATUS_ALREADY_OWNED\x10\x01\x12\x15\n" +
	"\x11LEASE_STATUS_BUSY\x10\x02\x12\x16\n" +
	"\x12LEASE_STATUS_STALE\x10\x03\x12\x1a\n" +
	"\x16LEASE_STATUS_NOT_READY\x10\x04\x12\"\n" +
	"\x1eLEASE_STATUS_KEY_LIMIT_REACHED\x10\x05\x12\x1e\n" +
	"\x1aLEASE_STATUS_KEY_TOO_LARGE\x10\x062V\n" +
	"\bRedLease\x12J\n" +
	"\vLeaseStream\x12\x1a.redlease.v1.ClientRequest\x1a\x1b.redlease.v1.ServerResponse(\x010\x01BAZ?github.com/udovenkoav1981/RedLease/proto/redlease/v1;redleasev1b\x06proto3"

var (
	file_redlease_v1_redlease_proto_rawDescOnce sync.Once
	file_redlease_v1_redlease_proto_rawDescData []byte
)

func file_redlease_v1_redlease_proto_rawDescGZIP() []byte {
	file_redlease_v1_redlease_proto_rawDescOnce.Do(func() {
		file_redlease_v1_redlease_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redlease_v1_redlease_proto_rawDesc), len(file_redlease_v1_redlease_proto_rawDesc)))
	})
	return file_redlease_v1_redlease_proto_rawDescData
}

var file_redlease_v1_redlease_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redlease_v1_redlease_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_redlease_v1_redlease_proto_goTypes = []any{
	(LeaseStatus)(0),        // 0: redlease.v1.LeaseStatus
	(*LeaseID)(nil),         // 1: redlease.v1.LeaseID
	(*ClientRequest)(nil),   // 2: redlease.v1.ClientRequest
	(*ServerResponse)(nil),  // 3: redlease.v1.ServerResponse
	(*AcquireRequest)(nil),  // 4: redlease.v1.AcquireRequest
	(*RenewRequest)(nil),    // 5: redlease.v1.RenewRequest
	(*ReleaseRequest)(nil),  // 6: redlease.v1.ReleaseRequest
	(*GetTTLRequest)(nil),   // 7: redlease.v1.GetTTLRequest
	(*AcquireResponse)(nil), // 8: redlease.v1.AcquireResponse
	(*RenewResponse)(nil),   // 9: redlease.v1.RenewResponse
	(*ReleaseResponse)(nil), // 10: redlease.v1.ReleaseResponse
	(*GetTTLResponse)(nil),  // 11: redlease.v1.GetTTLResponse
}
var file_redlease_v1_redlease_proto_depIdxs = []int32{
	4,  // 0: redlease.v1.ClientRequest.acquire:type_name -> redlease.v1.AcquireRequest
	5,  // 1: redlease.v1.ClientRequest.renew:type_name -> redlease.v1.RenewRequest
	6,  // 2: redlease.v1.ClientRequest.release:type_name -> redlease.v1.ReleaseRequest
	7,  // 3: redlease.v1.ClientRequest.get_ttl:type_name -> redlease.v1.GetTTLRequest
	8,  // 4: redlease.v1.ServerResponse.acquire:type_name -> redlease.v1.AcquireResponse
	9,  // 5: redlease.v1.ServerResponse.renew:type_name -> redlease.v1.RenewResponse
	10, // 6: redlease.v1.ServerResponse.release:type_name -> redlease.v1.ReleaseResponse
	11, // 7: redlease.v1.ServerResponse.get_ttl:type_name -> redlease.v1.GetTTLResponse
	1,  // 8: redlease.v1.AcquireRequest.lease_id:type_name -> redlease.v1.LeaseID
	1,  // 9: redlease.v1.RenewRequest.lease_id:type_name -> redlease.v1.LeaseID
	1,  // 10: redlease.v1.ReleaseRequest.lease_id:type_name -> redlease.v1.LeaseID
	0,  // 11: redlease.v1.AcquireResponse.status:type_name -> redlease.v1.LeaseStatus
	0,  // 12: redlease.v1.RenewResponse.status:type_name -> redlease.v1.LeaseStatus
	0,  // 13: redlease.v1.ReleaseResponse.status:type_name -> redlease.v1.LeaseStatus
	2,  // 14: redlease.v1.RedLease.LeaseStream:input_type -> redlease.v1.ClientRequest
	3,  // 15: redlease.v1.RedLease.LeaseStream:output_type -> redlease.v1.ServerResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_redlease_v1_redlease_proto_init() }
func file_redlease_v1_redlease_proto_init() {
	if File_redlease_v1_redlease_proto != nil {
		return
	}
	file_redlease_v1_redlease_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientRequest_Acquire)(nil),
		(*ClientRequest_Renew)(nil),
		(*ClientRequest_Release)(nil),
		(*ClientRequest_GetTtl)(nil),
	}
	file_redlease_v1_redlease_proto_msgTypes[2].OneofWrappers = []any{
		(*ServerResponse_Acquire)(nil),
		(*ServerResponse_Renew)(nil),
		(*ServerResponse_Release)(nil),
		(*ServerResponse_GetTtl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redlease_v1_redlease_proto_rawDesc), len(file_redlease_v1_redlease_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redlease_v1_redlease_proto_goTypes,
		DependencyIndexes: file_redlease_v1_redlease_proto_depIdxs,
		EnumInfos:         file_redlease_v1_redlease_proto_enumTypes,
		MessageInfos:      file_redlease_v1_redlease_proto_msgTypes,
	}.Build()
	File_redlease_v1_redlease_proto = out.File
	file_redlease_v1_redlease_proto_goTypes = nil
	file_redlease_v1_redlease_proto_depIdxs = nil
}
